// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearEmailContentCache():Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteUserPreference(arg1:string):Promise<void>;

export function DownloadAttachment(arg1:number,arg2:string):Promise<string>;

export function ForceRefreshEmailContent(arg1:number):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetActiveAccount():Promise<main.Account>;

export function GetEmailContent(arg1:number):Promise<main.EmailContent>;

export function GetEmails(arg1:number,arg2:number):Promise<main.EmailPage>;

export function GetFolders():Promise<Array<string>>;

export function GetPassword(arg1:number):Promise<string>;

export function GetUserPreference(arg1:string):Promise<string>;

export function GetUserPreferences():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function MarkEmailAsRead(arg1:number):Promise<void>;

export function RefreshEmails():Promise<void>;

export function SaveAccount(arg1:main.Account,arg2:string):Promise<void>;

export function SaveAttachment(arg1:number,arg2:string):Promise<string>;

export function SetActiveAccount(arg1:number):Promise<void>;

export function SetUserPreference(arg1:string,arg2:string):Promise<void>;
