// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearEmailContentCache() {
  return window['go']['main']['App']['ClearEmailContentCache']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteUserPreference(arg1) {
  return window['go']['main']['App']['DeleteUserPreference'](arg1);
}

export function DownloadAttachment(arg1, arg2) {
  return window['go']['main']['App']['DownloadAttachment'](arg1, arg2);
}

export function ForceRefreshEmailContent(arg1) {
  return window['go']['main']['App']['ForceRefreshEmailContent'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetEmailContent(arg1) {
  return window['go']['main']['App']['GetEmailContent'](arg1);
}

export function GetEmailSnippet(arg1) {
  return window['go']['main']['App']['GetEmailSnippet'](arg1);
}

export function GetEmails(arg1, arg2) {
  return window['go']['main']['App']['GetEmails'](arg1, arg2);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetUserPreference(arg1) {
  return window['go']['main']['App']['GetUserPreference'](arg1);
}

export function GetUserPreferences() {
  return window['go']['main']['App']['GetUserPreferences']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MarkEmailAsRead(arg1) {
  return window['go']['main']['App']['MarkEmailAsRead'](arg1);
}

export function RefreshEmails() {
  return window['go']['main']['App']['RefreshEmails']();
}

export function SaveAccount(arg1, arg2) {
  return window['go']['main']['App']['SaveAccount'](arg1, arg2);
}

export function SaveAttachment(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function SetUserPreference(arg1, arg2) {
  return window['go']['main']['App']['SetUserPreference'](arg1, arg2);
}
