// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DownloadAttachment(arg1, arg2) {
  return window['go']['main']['App']['DownloadAttachment'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetEmailContent(arg1) {
  return window['go']['main']['App']['GetEmailContent'](arg1);
}

export function GetEmails(arg1, arg2) {
  return window['go']['main']['App']['GetEmails'](arg1, arg2);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveAccount(arg1, arg2) {
  return window['go']['main']['App']['SaveAccount'](arg1, arg2);
}

export function SaveAttachment(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2);
}
